### ISSUE TITLE
Actividad 8 Practica 4y5 Lectura y escritura

### ISSUE THREAD

**Issue by ka194** [SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-equipo_-mejora#1]
[Practica_4_y_5_.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-4y5-lectura-y-escritura-de-un-contrato-equipo_-mejora/files/15279331/Practica_4_y_5_.pdf)

**Comment by josealfredo79** [comment]
Se necesita calificar....Bien hecho y revisado...19
